### ISSUE TITLE
ERROR: 2 UNKOWN: Stream removed

### ISSUE THREAD

**Issue by RaLazo** [TheIanSim/FabCar#3]
Hey there,
by runnig the script ` fabcar-backend.js` we get the follwing output:
```
Listening on port 4001
Connected to client with socket ID xV50Ew5hwVZCZ0ZHAAAA
Successfully loaded user1 from persistence
Block updater error { Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'Stream removed' }
```
It shows the error everytime we want to excute a query for example `QueryAll`l:

```
error from query =  { Error: 2 UNKNOWN: Stream removed
    at Object.exports.createStatusError (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/blockchain/chain/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'Stream removed' }
```

Do you have any idea how to fix this issue ?

Kind Regards 

Rafael

**Comment by rschildxc** [comment]
@RaLazo I have the same  Error: 2 UNKNOW: Stream removed !

**Comment by masanchez91** [comment]
Could they solve the error?
I have the same error.

I can't solve it. I haven't succeeded. Can you help me?

@RaLazo @rschildxc  @TheIanSim

**Comment by RaLazo** [comment]
Sorry we can't really fix the ERROR.

**Comment by RaLazo** [comment]
We tried to rebuild the backend with a different lib, but it doesn't really work fine.
